# Deep Learning Study

## Functional API

### 분류문제

In [1]:
from sklearn.datasets import load_boston

In [2]:
boston = load_boston()

C:\Users\User\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California 

In [3]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [4]:
import tensorflow as tf
from tensorflow import keras

In [18]:
keras.backend.clear_session()

il= keras.layers.Input(shape=(13,))
ol= keras.layers.Dense(1)(il)

model = keras.models.Model(il,ol)

model.compile(loss='mse', optimizer='adam')

In [19]:
model.fit(x,y,epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 40084.6992
Epoch 2/10
16/16 [==============================] - 0s 997us/step - loss: 34448.1484
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 29419.2930
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 24898.2188
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 20948.9824
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 17515.5781
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 14548.4922
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 11985.0176
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 9819.8926
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 7975.8477


In [20]:
y_pred= model.predict(x)
y_pred[:5].reshape(-1)

array([-53.024353, -59.915142, -56.833183, -54.767067, -56.17633 ],
      dtype=float32)

In [17]:
y[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

### 회귀문제

In [21]:
from sklearn.datasets import load_breast_cancer

In [22]:
cancer = load_breast_cancer()

In [23]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape , y.shape

((569, 30), (569,))

In [24]:
keras.backend.clear_session()

il=keras.layers.Input(shape=(30,))
ol=keras.layers.Dense(1, activation='sigmoid')(il)

model = keras.models.Model(il,ol)

model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

In [25]:
model.fit(x,y, epochs=10, verbose=1)

Epoch 1/10
18/18 [==============================] - 0s 1ms/step - loss: 129.6218 - accuracy: 0.6274
Epoch 2/10
18/18 [==============================] - 0s 1ms/step - loss: 110.6040 - accuracy: 0.6274
Epoch 3/10
18/18 [==============================] - 0s 1ms/step - loss: 92.2821 - accuracy: 0.6274
Epoch 4/10
18/18 [==============================] - 0s 1ms/step - loss: 73.5893 - accuracy: 0.6274
Epoch 5/10
18/18 [==============================] - 0s 1ms/step - loss: 55.2183 - accuracy: 0.6257
Epoch 6/10
18/18 [==============================] - 0s 1ms/step - loss: 37.1585 - accuracy: 0.5888
Epoch 7/10
18/18 [==============================] - 0s 1ms/step - loss: 20.9303 - accuracy: 0.4025
Epoch 8/10
18/18 [==============================] - 0s 1ms/step - loss: 13.2745 - accuracy: 0.1845
Epoch 9/10
18/18 [==============================] - 0s 1ms/step - loss: 12.5441 - accuracy: 0.2056
Epoch 10/10
18/18 [==============================] - 0s 1ms/step - loss: 11.8182 - accuracy: 0.1880


In [28]:
y_pred= model.predict(x)
y_pred[:5].reshape(-1)

array([9.9969935e-01, 1.0000000e+00, 9.9999946e-01, 2.4339155e-08,
       9.9999905e-01], dtype=float32)