# Deep Learning Study

### Sequential API

Sequential은 레이어를 순차적으로 쌓고 일자적인 느낌이다.

### Linear Regression

#### 회귀문제!

In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

C:\Users\User\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California 

In [4]:
x = boston.data
y = boston.target

In [6]:
#꼭 shape를 사용해서 파악을 해야한다.

x.shape, y.shape

((506, 13), (506,))

In [16]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape=(13,)))
model.add(keras.layers.Dense(1))

model.compile(loss='mse', optimizer='adam')

In [17]:
#학습시키기
model.fit(x,y, epochs=10, verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 16799.5684
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 13293.0088
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 10388.2754
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 7951.7471
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 6033.0352
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 4541.6201
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 3389.1299
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 2511.7568
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 1881.4586
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 1429.9425


In [18]:
model.predict(x).reshape(-1)

array([ 35.47984   ,  37.1095    ,  38.446667  ,  37.452297  ,
        36.960896  ,  35.9695    ,  39.78831   ,  37.263123  ,
        38.619003  ,  37.67049   ,  37.63902   ,  37.69845   ,
        44.24222   ,  45.429943  ,  41.895985  ,  46.148323  ,
        49.001034  ,  43.58812   ,  44.470417  ,  44.677563  ,
        41.96173   ,  42.55816   ,  43.468365  ,  42.46039   ,
        42.56553   ,  39.31636   ,  41.91126   ,  39.27627   ,
        41.524952  ,  41.92475   ,  42.21304   ,  39.87016   ,
        38.999172  ,  40.98944   ,  35.797085  ,  41.606476  ,
        42.02434   ,  45.165813  ,  46.933727  ,   1.0070249 ,
         1.420631  ,  44.824947  ,  44.25477   ,  45.19773   ,
        40.647896  ,  41.93202   ,  42.97264   ,  36.469616  ,
        37.963387  ,  39.281296  ,  29.777412  ,  26.324308  ,
        31.56547   ,  32.136314  ,  25.978151  , -11.538153  ,
         1.7696191 , -16.248653  ,  30.650627  ,  28.917612  ,
        26.98247   ,  22.645475  ,  25.516022  ,  29.67

In [19]:
# 예측하기
y_pred = model.predict(x)
y_pred[:5].reshape(-1)

array([35.47984 , 37.1095  , 38.446667, 37.452297, 36.960896],
      dtype=float32)

In [15]:
y[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

#### 분류문제

In [20]:
from sklearn.datasets import load_breast_cancer

In [21]:
cancer = load_breast_cancer()

In [22]:
x = cancer.data
y = cancer.target

x.shape, y.shape

((569, 30), (569,))

In [23]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(30,)))
model.add( keras.layers.Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [24]:
model.fit(x,y, epochs=10, verbose=1)

Epoch 1/10
18/18 [==============================] - 0s 1ms/step - loss: 34.4358 - accuracy: 0.5431
Epoch 2/10
18/18 [==============================] - 0s 1ms/step - loss: 25.5573 - accuracy: 0.2689
Epoch 3/10
18/18 [==============================] - 0s 1ms/step - loss: 23.8393 - accuracy: 0.2109
Epoch 4/10
18/18 [==============================] - 0s 1ms/step - loss: 23.1073 - accuracy: 0.2162
Epoch 5/10
18/18 [==============================] - 0s 1ms/step - loss: 22.3295 - accuracy: 0.2408
Epoch 6/10
18/18 [==============================] - 0s 1ms/step - loss: 21.5400 - accuracy: 0.2619
Epoch 7/10
18/18 [==============================] - 0s 1ms/step - loss: 20.7724 - accuracy: 0.2496
Epoch 8/10
18/18 [==============================] - 0s 1ms/step - loss: 19.8885 - accuracy: 0.2742
Epoch 9/10
18/18 [==============================] - 0s 1ms/step - loss: 19.0662 - accuracy: 0.2847
Epoch 10/10
18/18 [==============================] - 0s 1ms/step - loss: 18.3502 - accuracy: 0.3076


In [25]:
y_pred = model.predict(x)
y_pred[:5]

array([[1.0000000e+00],
       [1.0000000e+00],
       [9.5695436e-01],
       [1.0000000e+00],
       [5.5960938e-30]], dtype=float32)

In [26]:
y[:5]

array([0, 0, 0, 0, 0])